@extends('frontend.layouts.app')

@section('title', 'Privacy Policy')

@section('styles')
    <style>
        .beefup__head {
            white-space: normal !important;
        }

    </style>
@endsection

@section('content')
    <div id="header-bottom-wrap" class="is-clearfix">
        <div id="header-bottom" class="site-header-bottom">
            <div id="header-bottom-inner" class="site-header-bottom-inner ">
                <section class="hero page-title is-medium has-text-centered blog-single"
                    style="background: #812323 url({{ asset('/frontend/assets/images/page-header/3.jpg') }}) no-repeat top center; background-size: cover;}">
                    <div class="hero-body">
                        <div class="container">
                            <h1>Vivo Moments Privacy Policy</h1>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    <div id="content-main-wrap" class="is-clearfix">
        <div id="content-area" class="site-content-area">
            <div id="content-area-inner" class="site-content-area-inner">
                <section class="section  is-clearfix" style="background-color: #f6f6f6;">
                    <div class="container" style="background-color: #fff;">
                        <div class="m-4" style="padding: 50px 40px;">

                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:32px;font-family:vivo;">Vivo Moments Privacy Policy</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">Welcome! vivo Mobile Communication Co., Ltd. (&quot;vivo,&quot; &quot;we&quot; or &quot;us&quot;) respects your personal data and fulfills all mandatory requirements. This vivo Privacy Policy (hereinafter referred as &quot;Privacy Policy&quot;) describes how we process your personal data when you interact with vivomoments.com, vivo.com, vivoglobal.com or other websites of vivo, or when you use or visit products, services, applications, functions, or other digital properties of vivo (e.g., vivoCloud, vivo&rsquo;s User Experience Improvement Plan) and any other locations where this Privacy Policy may be posted (collectively, the &quot;Services&quot;), for the purposes of applicable data protection legislation. Please read our privacy practices carefully and <strong>Contact Us</strong> if you have any questions.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">1.Terms and Definitions</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">Data controller</span></strong><span style="font-size:16px;font-family:vivo;">&nbsp;means the legal entity (alone or jointly with others) determining the purposes and means of the processing of personal data. vivo moments is the data controller, if not otherwise determined by law.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">Personal data</span></strong><span style="font-size:16px;font-family:vivo;">&nbsp;means any information relating to an identified or identifiable natural person (&quot;data subject&quot;). An identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person; You (user or visitor of the Services) are the data subject.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">International transfer</span></strong><span style="font-size:16px;font-family:vivo;">&nbsp;means transmission of personal data to the territory of a foreign state, public authority of a foreign state, foreign individual or foreign legal entity.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">2.Legal Grounds for the Processing of Personal Data</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">Vivo moments will process your personal data and photos you share only where there are legal grounds to do so. Those grounds include the following:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(a)Consent</span></strong><span style="font-size:16px;font-family:vivo;">: You have provided your consent to the processing of your personal data and use your photos.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(b)Legal obligations</span></strong><span style="font-size:16px;font-family:vivo;">: The processing of your personal data and photos you shared is required or authorized by applicable laws, or relates to suspected unlawful activity, serious misconduct, legal proceedings or law enforcement.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(c)Legitimate interests</span></strong><span style="font-size:16px;font-family:vivo;">: The processing of your personal data is necessary for the purposes of our legitimate interests. We believe that our processing of your personal data is within our legitimate interests and within your reasonable expectations in a number of situations, including but not limited to:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; To help us understand our Participants better and provide improved, more relevant services to them;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; To ensure that our Services run smoothly;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; To help us keep our systems secure and prevent unauthorized access or cyber-attacks;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; To protect the rights, property, or safety of us, or any of our affiliates, business partners, or Participants</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; To anonymize personal data (e.g., for research and statistical purposes) and</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; To drive commercial value for the benefit of our shareholders, where not outweighed by any potential prejudice to you.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">3.Information We Collect</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(a)Registration and account information</span></strong><span style="font-size:16px;font-family:vivo;">: You may use our Services without telling us who you are or revealing any personal data about yourself. If you choose to register for an account (vivo moments Account or other account available at vivo) with us, we require you to create a username and password. You will be asked to give us your personal data during the registration and such personal data is not anonymous to us. When you register an account or otherwise engage with our Services, you may provide personal data such as <strong>name</strong>, age, gender, email address, phone number, and other relevant information. We may request you to provide identity information for verification purpose if so required or authorized by applicable laws.&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(b)Information to respond to your requests:&nbsp;</span></strong><span style="font-size:16px;font-family:vivo;">You may give us your personal data so we can respond to your questions and requests (in relation to exercising your rights, using customer service or otherwise), including your identify information, contact information and the Services you&rsquo;re inquiring about. When you communicate with our staff, the communications will be transmitted through our systems.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">&nbsp;(c)Mobile information and device data information:&nbsp;</span></strong><span style="font-size:16px;font-family:vivo;">We may collect additional information from you if you access our Services through a mobile device, e.g., country or region code of your device, <strong>IMEI (International Mobile Equipment Identity)</strong>, eMMC ID (embedded multimedia card), GAID (Google Advertising ID), GUID, UUID, UFS ID (universal flash storage), SIM and IMSI (International Mobile Subscriber Identity), or other unique identifier of the device, device module, version of or other information about your device&rsquo;s operating system, CPU information, storage condition, configuration and parameter of screen, IP address, MAC address, mobile carrier, postal code, language and other settings,<strong>&nbsp;location or GPS/geo-location</strong>, applications information, and other information that may relate to the mobile device you use.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(d)Log information:&nbsp;</span></strong><span style="font-size:16px;font-family:vivo;">When you visit or use our Services, we may collect usage information sent to us by your computer, mobile, or other access device that tells us the number of visitors to the Services and when and how you are using the Services (&quot;usage information&quot;), such as the time and duration of your use of the Services, the search query terms entered through the Services, logs that may refer to you use of or the error in your use of the Services, and other usage log related to the Services. We will store your consent record for our privacy terms for 5 years in order to confirm your authorization of data collection, and hence to prevent us from unauthorized collecting of your personal data; we will store your rights complaints record for 5 years, in order to track the processing status and promote the proper resolution of related issues.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(e)Information from other sources:</span></strong><span style="font-size:16px;font-family:vivo;">&nbsp;The information we collect may be combined with information from outside records (e.g., demographic information, navigation information, additional contact information) that we have acquired in accordance with the law, from sources such as publicly available information, social media. vivo moments will process your personal data in this way only where there are legal grounds to do so.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(f)Other Information:</span></strong><span style="font-size:16px;font-family:vivo;">&nbsp;When you use some of the Services and such Services may require specific use of your information, we will specify such information in separate terms, agreements, or privacy policies and will collect, process, use, or transfer such information according thereto and get your consent where appropriate.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">We do not generally ask you for sensitive personal data, i.e. personal data that reveal racial or ethnic origin, political opinions, religious or philosophical beliefs, criminal records, or trade union or professional association membership, genetic data and biometric data for the purpose of uniquely identifying a natural person, and data concerning health or data concerning a natural person&rsquo;s sex life or sexual orientation. However, if we need to collect or process sensitive personal data (such as facial feature, fingerprint feature, voice recording, heart rate, step count, etc.) in other circumstances, we will do so with your consent or where we are otherwise required or permitted by law.</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">4.Purposes of Processing of Personal Data</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">vivomoments will process your personal data to fulfill the following purposes:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(a)Operate our Services</span></strong><span style="font-size:16px;font-family:vivo;">: We process collected personal data to (i) provide, maintain, improve, protect, and develop all of our services, products, content, and advertisements; (ii) send notices to you of our software updates, updated policies or other information that we believe may be important to you; (iii) analyze and develop data and information on the use of our services and products to provide better services and products; (iv) interact with you about your device, services, or any of your questions and requests; (v) administer promotional activities, such as sweepstakes, contests, or other similar events; (vi) conduct after-sales and customer support activities; (vii) judge software compatibility, provide customized products or services.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(b)Analyze and aggregate non-personal usage information</span></strong><span style="font-size:16px;font-family:vivo;">: We use aggregate and anonymized usage information about our users, technical usage data and non-personal data to analyze the Services and prepare aggregated reports to, for example, provide better products and services to our customers.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(c)Understand how you use our products</span></strong><span style="font-size:16px;font-family:vivo;">: We may ask you for your opinions on our products and services and to understand how you use our products/services, with your separate consent if required.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(d)Marketing</span></strong><span style="font-size:16px;font-family:vivo;">: We will only send you marketing, advertising, or promotional materials where you have previously provided explicit opt-in consent to receipt of such communications. We will ensure that each electronic marketing communication contains a link allowing you to unsubscribe from such communications.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">&nbsp;(e)Account management</span></strong><span style="font-size:16px;font-family:vivo;">: We may use information (including your personal information) to register and close your account, maintain and update our records, and similar activities in connection with our Services.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">We may not be able to do these things without your personal data. For example, we may not be able to communicate with you and deal with your enquiries.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">5.Ways of Processing of Personal Data</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">We will carry out the following operations on your personal data with the use of non-automatic means of processing: collection, recording, systematization, accumulation, storage, alteration (update, modification), retrieval, use, transfer (provision, access), depersonalization, blocking, and deletion (destruction) of personal data. Normally, we will not use automatic means like &quot;profiling&quot; in our data processing. If we need to do such automatic processing in other circumstances, we will do so after getting your explicit consent.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">We are required to ensure such processing is subject to suitable safeguards, including reasonable steps to ensure personal data is accurate, complete, up-to-date and relevant, and your rights to access and correct personal data about you.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">6.Retention Period</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">We process your personal data for as long as is necessary to fulfill the purpose for which it was collected. We build upon the following criteria to determine the retention period of personal data about you:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(a)The duration for which the personal data is used to provide you with a service;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(b)Your request, or obligations under a contract with you;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(c)Regulatory or legal obligation.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">When it is no longer necessary to retain your personal data, or if you cancel your account or withdraw your consent, we will delete related personal data that we hold about you from our systems, unless we are entitled (or obliged) to continue processing your personal data on other legal grounds (e.g. for archiving purposes in the public interest, or for scientific or historical research purposes). While we will endeavor to permanently erase your personal data once it reaches the end of its retention period, some of your personal data may still exist within our systems, for example if it is waiting to be overwritten. For our purposes, such data has been put beyond use, meaning that, while it still exists in the electronic ether, our employees will not have any access to it or use it again.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">7.How vivo moments Shares Your Personal Data</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">Personal data may be shared with:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(a)vivoMoments Affiliated Entities.&nbsp;</span></strong><span style="font-size:16px;font-family:vivo;">We may share the personal data we collect about you with the vivo group companies and their and our affiliates and subsidiaries. vivomoments affiliated entities may process personal data on the same bases as described in this Privacy Policy.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(b)Authorized Partners.</span></strong><span style="font-size:16px;font-family:vivo;">&nbsp;We may disclose your personal data to authorized partners of vivo, including as follows: operators, distributors and sales partners, advertisement companies, research companies, third party data service providers (i.e. our data processors), consignment suppliers, logistics companies, online service suppliers, proxy agencies, e-commerce platforms, third party application services, professional advisers (e.g. lawyers, accountants and auditors), insurers and investigators. We will list the registered information and the data interaction details of related third parties in the Privacy Terms of specific service. We require authorized partners to comply with applicable data protection legislation and to take necessary and reasonable measures to protect your information. vivomoments will never allow any authorized third party to use your personal data for any other purpose other than this Privacy Policy.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(c)Legal and law enforcement.</span></strong><span style="font-size:16px;font-family:vivo;">&nbsp;We might be required to disclose your personal data by local judicial or governmental authorities, agencies or as mandated under applicable laws.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">(d)Change of control &ndash; New Owners.&nbsp;</span></strong><span style="font-size:16px;font-family:vivo;">In the event of any actual or prospective merger, restructuring or bankruptcy, vivo may also provide your personal data to related third parties without further consent from you.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">When sharing your personal data with vivo Affiliated Entities, Authorized Partners and New Owners, we require that they securely store the personal data we provide to them and all such entities are contractually bound by us to keep the personal data confidential.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">8.Your Rights</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">Being a data subject, you have other rights with respect to your personal data in accordance with applicable data protection legislation. You can access your personal data, require its rectification, blocking, or deletion by sending your request to&nbsp;</span><a href="https://www.vivo.com/global/about-vivo/privacy-support" target="_self"><strong><span style="font-size:16px;font-family:vivo;color:blue;">https://www.vivo.com/global/about-vivo/privacy-support</span></strong></a><span style="font-size:16px;font-family:vivo;">&nbsp;as set out in Contact Us Section of this Privacy Policy. We shall at no time however be responsible/ liable for the authenticity/ veracity of the information you provide. Please note that we may keep a record of your communications to help us resolve any issues which you raise.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">You have the following rights in relation to your personal data:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">A.Right to object</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">This right enables you to object to us processing your personal data where we do so for one of the following reasons:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; because it is in our legitimate interests to do so;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; to enable us to perform a task in the public interest or exercise official authority;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; to send you direct marketing materials; or</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; for scientific, historical, research, or statistical purposes.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">B.Right to withdraw consent</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">Where we have obtained your consent to process your personal data for certain activities (for example, for marketing), you may withdraw consent at any time by going to the Settings on your device or contacting us, and we will cease to use your personal data for that purpose unless we consider that there is an alternative legal basis to justify our continued processing of your personal data for that purpose, in which case we will inform you of this basis.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">You have the right to withdraw your consent to the processing of your personal data any time with effectiveness for the future. To do this, please send your withdrawal request to&nbsp;</span><a href="https://www.vivo.com/global/about-vivo/privacy-support" target="_self"><strong><span style="font-size:16px;font-family:vivo;color:blue;">https://www.vivo.com/global/about-vivo/privacy-support</span></strong></a><span style="font-size:16px;font-family:vivo;">. Your personal data will be deleted within a reasonable time period after receipt of your withdrawal. We draw your attention to the fact that we may continue processing your personal data if we are entitled (or obliged) to continue processing your personal data on other legal grounds.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">C.Data subject access requests</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">You may ask us for a copy of the information we hold about you at any time, and request us to modify, update or delete such information. Additionally, you have the right to access the following information:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; the purposes of the processing of your personal data;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; the categories of personal data concerned;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; the recipients or categories of recipient of the personal data;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; the envisaged period for which the personal data will be stored, or the criteria used to determine that period;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; the existence of the right to request from us rectification or erasure of personal data, restriction of processing of personal data concerning you, or to object to such processing;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; the right to lodge a complaint with a supervisory authority;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; where the personal data are not collected from you, any available information as to their source;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; the existence of automated decision-making, including profiling;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; if personal data are transferred to a third country or to an international organization, the appropriate safeguards relating to the transfer.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">If we provide you with access to the information we hold about you, we will not charge you for this unless permitted by law. If you request further copies of this information from us, we may charge you a reasonable administrative cost. Where we are legally permitted to do so, we may refuse your request. If we refuse your request we will always tell you the reasons for doing so.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">D.Right to erasure</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">You have the right to request that we &quot;erase&quot; your personal data in certain circumstances. Normally, this right exists where:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; It is no longer necessary for us to process your personal data;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; You have withdrawn your consent to us using your personal data, and there is no other valid reason for us to continue;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; The personal data has been processed unlawfully;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; It is necessary for the personal data to be erased in order for us to comply with our obligations under law; or</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; You object to the processing and we are unable to demonstrate overriding legitimate grounds for our continued processing.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">We would only be entitled to refuse to comply with your request for erasure in limited circumstances and we will always tell you our reason for doing so. When complying with a valid request for the erasure of personal data we will take all reasonably practicable steps to delete the relevant personal data.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">E.Right to restrict processing</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">You have the right to request that we restrict our processing of your personal data in certain circumstances, for example if you dispute the accuracy of the personal data that we hold about you or you object to our processing of your personal data for our legitimate interests. If we have shared your personal data with third parties, we will notify them about the restricted processing unless this is impossible or involves disproportionate effort. We will, of course, notify you before lifting any restriction on processing your personal data.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">F.Right to rectification</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">You have the right to request that we rectify any inaccurate or incomplete personal data that we hold about you. If we have shared this personal data with third parties, we will notify them about the rectification unless this is impossible or involves disproportionate effort. You may also request details of the third parties that we have disclosed the inaccurate or incomplete personal data to. Where we think that it is reasonable for us not to comply with your request, we will explain our reasons for this decision.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">G.Right of data portability</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">You have the right to transfer your personal data between service providers, provided that: 1) the personal data is processed by automated means; 2) the personal data has been provided to us by data subjects; and 3) the basis for processing is consent, or that the data are being processed to fulfil a contract or steps preparatory to a contract. In effect, this means that you are able to transfer the details we hold about you to another third party. To allow you to do so, we will provide you with your personal data in a commonly used machine-readable format so that you can transfer the personal data. Alternatively, we may directly transfer the personal data for you.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">H.Right to complain</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">You have the right to lodge a complaint with the relevant supervisory authority.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">Please be aware that we will obtain and retain information about the exercises of your rights, for example, your consent to and your withdrawal of consent to certain privacy terms subject hereto, and your request to delete the data we collect from you under this Privacy Policy.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">9.Cookies</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">We may use tracking technologies (including e.g., <strong>unique device identifiers</strong>, referrer URL and location from your devices) when you use certain applications or features. Please refer to our separate <strong>Cookies policy</strong> for information about how we use certain technologies to enhance your online experience and customize our service to you.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">10.Third Party Links</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">Our Services may contain links to other third party websites, products and services, or use or offer products or services from third parties. Information collected by third parties is governed by their privacy practices. We encourage you to learn about the privacy practices of those third parties. We are not responsible for the privacy practices or the content of these third party sites.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">11.Security</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">vivomoments takes security measures to protect your information, including but not limited to technical and physical measures. However, please note that although we have implemented these measures, there is no security measure that can guarantee the absolute safety and security of your information. If you believe that your login credentials have been compromised, please contact us at once.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">When you use some vivo products, services, or applications, the personal data you share is visible to other users and in some cases search engines and the public and can be read, collected, used and retained by those other parties. You are responsible for the personal data you choose to share or submit in these instances. It is your responsibility to make sure that your personal data is accurate.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">Below are some examples of data security measures we undertake:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(a)Ensuring the security of the premises where the information systems used to process personal data are located. Such security shall prevent any uncontrolled access to such premises by persons having no rights to access such premises.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(b)Using technical means to protect the information including but not limited to encryption and anonymization techniques.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(c)Approving the list of persons who are authorized to access the information systems where the personal data are processed.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(d)Appointing a data protection officer.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(e)Identifying threats to the security of personal data while they are being processed in our information systems.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(f)Assessing the effectiveness of measures taken to ensure the security of personal data.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(g)Detecting instances of unauthorized access to personal data and taking appropriate measures to mitigate the effects of such unauthorized access.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(h)Taking all practicable measures to restore personal data which have been modified or destroyed as a result of unauthorized access.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(i)Monitoring measures taken to ensure the security of personal data and the level of protection of personal data information systems.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">(j)Establishing rules for access to personal data being processed in our information systems and recording all processing actions performed on personal data contained in our information systems.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">Please note that we hold personal information electronically and in hard copy form, both at our own premises and with the assistance of our service providers.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">12.Minors&apos; Privacy</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">The Services are not intended for minors as defined by applicable laws. We do not knowingly collect personal data via our Services about minors. We will only use or disclose minor information if (a) legally permissible; (b) the parent or other legal representative of the minor has provided consent; or (c) there are other legal grounds as per applicable data protection laws. If we accidentally collect a child&apos;s personal data without verified prior consent from the child&apos;s parents, we will to delete the data as soon as possible. If you believe a minor has provided personal data to us without parental/legal guardian consent, please <strong>Contact Us.</strong></span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">13.Storage and International Transfer</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">To provide the same level of data protection as that of the user&apos;s country/region and respond to users&apos; requests more efficiently, the location where data is stored varies for users in different countries/regions. For users in the European Economic Area, Turkey, Colombia, Peru, Australia, Andorra, Albania, Bosnia and Herzegovina, Macedonia, Monaco, Montenegro, Serbia, Croatia, The United Kingdom and Switzerland, your personal data will be stored on our server located in Singapore; for users in Russia, India and Kazakhstan, your personal data will be stored on our server located in your country; for users in other countries/regions, your personal data will be stored in our server located in Singapore.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">We want to make sure that your personal data is stored and transferred in a way which is secure. Where we transfer your personal data outside your country and where the country or territory in question does not maintain adequate data protection standards, we will take all reasonable steps to ensure that your data is treated securely and in accordance with applicable data protection legislation. For example, this could be:</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; By way of a data transfer agreement with a third party, incorporating standard contractual clauses to ensure that the third party protects your personal data; or</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; Where it is necessary for the conclusion or performance of a contract between ourselves and you, or between ourselves and a third party and the transfer is in your interests for the purposes of that contract (for example, if we need to transfer your data to a benefits provider based outside your country); or</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&middot; Where you have consented to the data transfer.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">We will obtain your consent separately before transferring your data to the country/region which does not offer the same level of protection as in your country.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">&nbsp;</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><strong><span style="font-size:16px;font-family:vivo;">14.Notification Regarding Updates</span></strong></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:normal;font-size:15px;'><span style="font-size:16px;font-family:vivo;">From time to time, we may update this Privacy Policy. In the event of any material changes to our Privacy Policy, you will be notified via e-mail or other available approaches. Please follow our most updated Privacy Policy at&nbsp;</span><a href="https://www.vivo.com/global/about-vivo/privacy-policy" target="_self"><strong><span style="font-size:16px;font-family:vivo;color:blue;">https://www.vivo.com/global/about-vivo/privacy-policy</span></strong></a><span style="font-size:16px;font-family:vivo;">.</span></p>
                            <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:107%;font-size:15px;'><span style="font-family:vivo;">&nbsp;</span></p>
                            <p><br></p>

                        </div>
                    </div>
                </section>
            </div>
            <!-- #content-area-inner -->
        </div>
        <!-- #content-area -->
    </div>
    <!-- #content-main-wrap -->
@endsection
